# Default values for Spring-Boot-Sample-Project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  name: "spring-boot-sample-project"

image:
  repository: 599278947730.dkr.ecr.eu-central-1.amazonaws.com/test
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 22

service:
  type: ClusterIP
  port: 80